name: conectar_app
description: "Front-end for Conéctar"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cpf_cnpj_validator: ^2.0.0
  dio: ^5.5.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  get_it: ^7.0.0
  google_fonts: ^6.2.1
  go_router: ^14.0.0
  jwt_decoder: ^2.0.1
  logger: ^2.4.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
    - .local.env
