name: Run Flutter Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Criar .env vazio para testes
        run: echo '' > .env && echo '' > .local.env
      - name: Run tests with coverage
        run: flutter test --coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
